# Application and Database Configuration
spring:
  application:
    name: student-management
  data:
    mongodb:
      #host: ${MONGODB_HOST_NAME}
      host: localhost
      port: 27017
      database: stms
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
